#!/bin/sh

# Change to update the frequency this runs.
sleep 2

xrandr --output "$(xrandr | awk '/ connected/{print $1; exit; }')" --auto

xev -root -event randr | \
grep --line-buffered 'subtype XRROutputChangeNotifyEvent' | \
while read foo ; do \
	xrandr --output "$(xrandr | awk '/ connected/{print $1; exit; }')" --auto
done
